### ISSUE TITLE
Design LPA backend in Apiary

### ISSUE THREAD

**Issue by jirihelmich** [linkedpipes/applications#1]
**Describe the solution you'd like**
Use API designer to suggest the API of your backend. Later, you can use the mock server for testing. We will go through the proposed API and suggest edits before you start implementing it.

**Comment by Ponsietta** [comment]
https://linkedpipes.docs.apiary.io/

**Comment by jirihelmich** [comment]
- [ ] Unify the naming.
- [ ] Rename the methods/calls in our diagram using your API calls to see their usage.
- [ ] Create diagrams that would demonstrate not just happy path workflows, but also possible failures.

**Comment by eghuro** [comment]
https://www.lucidchart.com/invitations/accept/3b8d5d74-fc9e-4e8e-b22c-14e1caeb671c
