### ISSUE TITLE
Rename development branch to develop

### ISSUE THREAD

**Issue by jirihelmich** [linkedpipes/applications#12]
`develop` is a standard and widely-used name. 

https://multiplestates.wordpress.com/2015/02/05/rename-a-local-and-remote-branch-in-git/

**Comment by aorumbayev** [comment]
@jirihelmich I have renamed the local development branch into develop and pushed develop to remote. However I do not have enough rights to remove the branch, I will ask my team to set `develop` as a new default branch and remove the old `development`.

**Comment by jirihelmich** [comment]
You should be able to do it now, it was set up as a default branch and you
cannot delete a default branch.

út 7. 8. 2018 v 15:46 odesílatel Altynbek Orumbayev <
notifications@github.com> napsal:

**Comment by aorumbayev** [comment]
@jirihelmich thanks for your help! The `development` branch is now removed. I will tell the team to transfer their local commits (if there are any) to new `develop` branch.
