### ISSUE TITLE
Give us access to files on HackMD.io

### ISSUE THREAD

**Issue by jirihelmich** [linkedpipes/applications#15]

**Comment by jirihelmich** [comment]
https://hackmd.io/lymLxN5AR4KTX4x3kPyiiQ#

**Comment by jirihelmich** [comment]
Pls add this link to readme file.

**Comment by aorumbayev** [comment]
@jirihelmich - the link was added to the readme on dev branch.

**Comment by jirihelmich** [comment]
Feel free to close a completed issue.
