### ISSUE TITLE
Basic integration with LP-Discovery

### ISSUE THREAD

**Issue by jirihelmich** [linkedpipes/applications#16]
Use the API (https://github.com/linkedpipes/discovery/blob/master/src/conf/routes) to achieve the following:
- [ ] start discovery
- [ ] poll status
- [ ] handle a finished discovery (both success and failure) in some basic way

**Comment by jakubklimek** [comment]
Current discovery configurations:
https://github.com/linkedpipes/discovery/tree/master/data/rdf/discovery-input/discovery
