### ISSUE TITLE
Frontend wireframes in online tools

### ISSUE THREAD

**Issue by jirihelmich** [linkedpipes/applications#2]
**Describe the solution you'd like**
Use some online tool like draw.io or https://moqups.com/ (choose your own) to create wireframes of the frontend of your application. Store the export from that tool in this GitHub repo. We will review the wireframes before you start implementing the UI.

**Comment by jirihelmich** [comment]
- [ ] Iterate on this so that you are happy with the results.
- [ ] Move it to some online tool as mentioned above.

**Comment by Ponsietta** [comment]
https://app.moqups.com/ponsietta/LMyuSmiQKD/view
