### ISSUE TITLE
Request to add extra priviliges to enable Travis CI

### ISSUE THREAD

**Issue by aorumbayev** [linkedpipes/applications#24]
@jirihelmich @jakubklimek , I know that i have already mentioned that in the gitter, but just to keep things consistent, I'm creating a github issue for that. 

Once access will be granted, travis enabled and I'll test it on dev - the issue will be closed.

**Comment by aorumbayev** [comment]
@jirihelmich @jakubklimek - Thanks I've just received the invite to become a member of lp and I can now see the repos inside travis. However as you can see on screenshot below, there is still not enough privileges for me to enable travis for repo. Can I ask you to either add extra privileges to me or simply enable the travis by yourself ? After that i should be able to test the current travis script on dev branch.

<img width="682" alt="screenshot 2018-09-05 21 00 13" src="https://user-images.githubusercontent.com/7698600/45114982-d0982f00-b14e-11e8-880b-76a5ba201666.png">

**Comment by jakubklimek** [comment]
I enabled Travis CI for the repo. Is it better now?

**Comment by aorumbayev** [comment]
Looks good. Build was successfull, both frontend and backend images are pushed to dockerhub. I have currently set my dockerhub id and password in env variables in travis. I am assuming issue can be closed now. @jakubklimek 

<img width="957" alt="screenshot 2018-09-06 18 48 06" src="https://user-images.githubusercontent.com/7698600/45172399-845bf600-b205-11e8-9747-4362fc6bc24b.png">
