### ISSUE TITLE
Research technology stack for backend

### ISSUE THREAD

**Issue by jirihelmich** [linkedpipes/applications#3]
**Describe the solution you'd like**
Create a list of a few backend technologies you would like to consider for building your backend. Write down (dis)advantages and sort them by your ranking to choose a winner. Required FW to include: Play 2.7

**Comment by Ponsietta** [comment]
Backend research summary at: https://docs.google.com/document/d/1tsfxb8YyJSiuKlu4XNA3Qtq1LQde3QB54qOIsZcwLUU/edit

**Comment by jirihelmich** [comment]
You have concluded it will be Java, but I haven't seen any particular framework in there. Can you elaborate?
