### ISSUE TITLE
Failed to publish advanced filter map

### ISSUE THREAD

**Issue by jakubklimek** [linkedpipes/applications#561]
When I created and published an Advanced filter map, I got this error:

![image](https://user-images.githubusercontent.com/718827/60414092-6a960000-9bd7-11e9-84de-23ddd36bb282.png)

I was logged in as https://klimek.lpsolid.eu:8443/profile/card#me

**Comment by jakubklimek** [comment]
Actually, this happend with a clean account. When I did that fro the second time, it was actually published. Maybe connected to directory creation?

**Comment by aorumbayev** [comment]
@jakubklimek yes it was related to directory creation, fixed in the final release v1.0
