### ISSUE TITLE
Docker compose fails on instantiating reverse proxy

### ISSUE THREAD

**Issue by jvanulde** [linkedpipes/applications#661]
**Describe the bug**
Using the instructions provided in the readme file, I attempted to get an instance up and running with Docker compose but it fails.

**To Reproduce**
1. `$ curl https://raw.githubusercontent.com/linkedpipes/applications/master/lpa-cli.sh -o lpa-cli.sh && chmod +x lpa-cli.sh && ./lpa-cli.sh --production-no-cloning`
2. See error:

    `ERROR: for lpa-reverse-proxy  Cannot start service nginx: OCI runtime create failed: container_linux.go:345: starting container process caused "process_linux.go:430: container init caused \"rootfs_linux.go:58: mounting \\\"/lpa_temp/docker/nginx-prod.conf\\\" to rootfs \\\"/var/lib/docker/overlay2/39ec327cbdbd8d7b43caac145be74f67a7cfe5e3fec20ea807ede32e441efffe/merged\\\" at \\\"/var/lib/docker/overlay2/39ec327cbdbd8d7b43caac145be74f67a7cfe5e3fec20ea807ede32e441efffe/merged/etc/nginx/nginx.conf\\\" caused \\\"not a directory\\\"\"": unknown: Are you trying to mount a directory onto a file (or vice-versa)? Check if the specified host path exists and is the expected type`

    `ERROR: for nginx  Cannot start service nginx: OCI runtime create failed: container_linux.go:345: starting container process caused "process_linux.go:430: container init caused \"rootfs_linux.go:58: mounting \\\"/lpa_temp/docker/nginx-prod.conf\\\" to rootfs \\\"/var/lib/docker/overlay2/39ec327cbdbd8d7b43caac145be74f67a7cfe5e3fec20ea807ede32e441efffe/merged\\\" at \\\"/var/lib/docker/overlay2/39ec327cbdbd8d7b43caac145be74f67a7cfe5e3fec20ea807ede32e441efffe/merged/etc/nginx/nginx.conf\\\" caused \\\"not a directory\\\"\"": unknown: Are you trying to mount a directory onto a file (or vice-versa)? Check if the specified host path exists and is the expected type
ERROR: Encountered errors while bringing up the project.`

**Expected behavior**
Running stack.

**Desktop (please complete the following information):**
 - OS: macOS High Sierra

**Comment by aorumbayev** [comment]
@jvanulde thanks for pointing this out, turned out to be a minor bug. 

Fixed in this [PR](https://github.com/linkedpipes/applications/pull/663).

Closing issue.
