### ISSUE TITLE
After running docker-compose.yml nothing happens when u click on authenticate in Frontend

### ISSUE THREAD

**Issue by unitw** [linkedpipes/applications#899]
When I run `curl https://raw.githubusercontent.com/linkedpipes/applications/master/lpa-cli.sh -o lpa-cli.sh && chmod +x lpa-cli.sh && ./lpa-cli.sh --production-no-cloning` and enter the Frontend login page (localhost:9001/login), select "LinkedPipes PODs" and click on "Authenticate" nothing happens.
Am I missing something or does it not work properly?

**Comment by aorumbayev** [comment]
@unitw there is a refactored release with support of latest NSS versions. I'll keep you updated, its gonna be merged this week

**Comment by unitw** [comment]
I can confirm it is working now :+1:
